# Generated by Django 6.0.2 on 2026-02-24 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tablets', models.IntegerField(default=0)),
                ('remaining_tablets', models.IntegerField(default=0)),
                ('tablets_per_dose', models.IntegerField(default=1)),
                ('medicine_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], default='regular', max_length=20)),
                ('schedules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('refill', 'Refill')], max_length=20)),
                ('tablets', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
