# Generated by Django 6.0.2 on 2026-02-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinehistory',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinehistory',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('refill', 'Refill'), ('dose', 'Dose Taken')], max_length=20),
        ),
    ]
