# Generated by Django 6.0.2 on 2026-02-24 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicinehistory_time_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('medicine', '💊 Medicine'), ('consultation', '🏥 Doctor Consultation'), ('lab', '🧪 Lab Test'), ('equipment', '🩺 Medical Equipment'), ('transport', '🚗 Transport'), ('other', '📦 Other')], default='other', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='medicinehistory',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='medicinehistory',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('refill', 'Refill'), ('dose', 'Auto Dose')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinehistory',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='medicines.medicine'),
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_key', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medicines.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'schedule_key', 'date')},
            },
        ),
    ]
