# Generated by Django 6.0.2 on 2026-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_expense_remove_medicinehistory_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='remaining_tablets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tablets_per_dose',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='total_tablets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinehistory',
            name='tablets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
