# Generated by Django 6.0.2 on 2026-02-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_medicine_remaining_tablets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
